language: node_js
dist: trusty
sudo: true
node_js: 5
env:
  - PATH=./node_modules/.bin:$PATH
install:
  - npm install purescript pulp bower purescript-psa
  - bower install
script:
  - pulp build --censor-lib
  - pulp test
